### PR TITLE
Fix H5FileImageWriter Callback

### PR DESCRIPTION
**Pull request by AjeyPaiK**
Fixes {#16}

1. After #16 was reported, upstream dlup was modified to return the scaled bounds. While writing H5 files, we now directly call this function to infer the scaled size of the WSI.

### CODE REVIEW

**Comment by AjeyPaiK** [comment]
@jonasteuwen Can you please review this PR? It's been here for some time.

**Comment by jonasteuwen** [comment]
@AjeyPaiK I think current dlup version should make this very easy on you. You can use `.get_scaled_bounds` for offset and size. Then you should probably also check if a new region_index happens in the sample index, because that won't be supported.

**Comment by AjeyPaiK** [comment]
@jonasteuwen Now, I think this is good to go!

**Comment by AjeyPaiK** [comment]
Issue addressed in #22

**Pull request closed without merging**
