### PR TITLE
Add possibility to override configs

### PR DESCRIPTION
**Pull request by jonasteuwen**
This commit implements a method to use the `additional_config` folder to override specific configurations.

### CODE REVIEW

**Comment by BPdeRooij** [comment]
The `additional_config` functionality works, but this is already a feature of Hydra ([Docs](https://hydra.cc/docs/advanced/search_path/)). Adding `../additional_config` to `train.yaml` as a Hydra searchpath achieves the same functionality, without cluttering the code with an unneeded plugin.
When hardcoding the location of `additional_config`, it might be good to add both an `__init__.py` and a `.gitkeep`.

**Comment by jonasteuwen** [comment]
I didn't get it to work the way I wanted (in the order that it will be overwritten). Did you manage to keep the functionality as mentioned? I think the plugin might still be interesting, as we can also extend it to read directly from repositories.

**Comment by BPdeRooij** [comment]
It seems that this plugin would still be interesting with the possibility to extend it to read directly from repositories.

I have two comments regarding the expected behaviour of this PR:
1. In `manipulate_search_path` no warning is given if the `additional_path` is not a directory. Perhaps logging something something simple, such as "Only using standard ahcore config folder for Hydra configurations.", would be good to avoid any confusion.
2. The `env.load_env` function starts searching recursively from `ahcore/utils` folder instead of the working directory. It will find the `.env` folder if it is in a parent folder but not when placed in the `tools` directory.

**Comment by jonasteuwen** [comment]
@BPdeRooij I believe I have addressed both concerns.

**Comment by BPdeRooij** [comment]
`dotenv.load_dotenv` expects an explicit file name. It does not start searching from `working_dir`. For this we could use `dotenv.find_dotenv(usecwd=True)` and give this as `dotenv_path`

**Comment by jonasteuwen** [comment]
Alright, but won’t the cwd be the folder where you’ve executed the command? Can you edit this in the PR?On Oct 30, 2023, at 10:01 AM, Bart ***@***.***> wrote:﻿
dotenv.load_dotenv expects an explicit file name. It does not start searching from working_dir. For this we could use dotenv.find_dotenv(usecwd=True) and give this as dotenv_path

**Review by BPdeRooij — APPROVED** [review]
LGTM.

**Pull request merged**
