### PR TITLE
H5 Writer for feature vectors.

### LINKED ISSUE #53: Extend `WriteH5Callback` to save feature vectors.
**Is your feature request related to a problem? Please describe.**
Currently, the `WriteH5Callback` and the H5 writer associated with it are desinged specifically to save outputs of a segmentation model. 

The callback can be extended to save feature vectors that we may be interested in with some small changes.

**Describe the solution you'd like**
NA

**Describe alternatives you've considered**
NA

**Additional context**
NA

### PR DESCRIPTION
**Pull request by AjeyPaiK**
This PR adds:

1. `H5TileFeatureWriter` to write feature vectors of WSI tiles to h5 files. 
2. The spatial configuration of the feature vectors correspond to the spatial configuration of their respective tiles in the WSI. Check below for a visual representation.
image

3. A test to check the new writer and its functions.
4. This issue fixes #53

### CODE REVIEW

**Review by EricMarcus-ai — APPROVED** [review]
LGTM

**Review by EricMarcus-ai — APPROVED** [review]
Let's see if this re-runs the tests.

**Review by EricMarcus-ai — APPROVED** [review]
And again.

**Comment by AjeyPaiK** [comment]
We fix rest of the pre-commit in a different PR.

**Pull request merged**
